import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideNav from "./ui-comps/SideNav";
import TopBar from "./ui-comps/topBar";
import LayoutWrapper from "./ui-comps/layoutWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const userData = "https://api.jsonbin.io/v3/b/67ec02e88a456b79668097d3";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SideNav />
        <TopBar />
        <div className="flex-1 ml-64 p-4">
          <LayoutWrapper>{children}</LayoutWrapper>
        </div>
      </body>
    </html>
  );
}
